Revert "Add Windows support"
This reverts commit 64e3e3767f5190e64c05ce656ae768bfec5c1c0f.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,6 +19,13 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: Fail
+      if: ${{ runner.os == 'Windows' }}
+      run: |
+        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
+        exit 1
+      shell: sh
+
     - name: Validate inputs
       id: validate-inputs
       env:
